export const FORECAST_START = 'REQ_FORECAST_START'
export const FORECAST_SUCCESS = 'REQ_FORECAST_SUCCESS'
export const FORECAST_FAIL = 'REQ_FORECAST_FAIL'
export const CHANGE_CITY_INPUT = 'CHANGE_CITY_INPUT'